server:
  port: 5001

spring:
  jpa:
    # PosgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    # MySQL
    # database-platform: org.hibernate.dialect.MySQL8Dialect
    # show-sql: true
    # hibernate:
    #   ddl-auto: update
  datasource:
    # PostgreSQL Data source
    url: jdbc:postgresql://localhost:5432/bankAccount
    username: postgres
    password: techbankRootPsw
    # MySQL Data source
    # url: jdbc:mysql://localhost:3306/bankAccount?createDatabaseIfNotExist=true
    # username: root
    # password: techbankRootPsw
  kafka:
    listener:
      ack-mode: manual_immediate
      poll-timeout: 900000
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bankaccConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    topic: BankAccountEvents